version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: forum_system
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      mynetwork:
        ipv4_address: 172.16.239.10

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      mynetwork:
        ipv4_address: 172.16.239.11
  app:
    container_name: app
    build: ./app
    ports:
      - "8080:8080"
    working_dir: /app
    depends_on:
      - mysql
      - redis
    volumes:
      - ./app:/app

    networks:
      mynetwork:
        ipv4_address: 172.16.239.12
    command: mvn clean spring-boot:run -Drun.profiles=docker
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/your_database_name_here?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: your_mysql_username_here
#      SPRING_DATASOURCE_PASSWORD: your_mysql_password_here
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1






